# @package _global_

defaults:
  - override /model: adversary/am.yaml
  - override /env: svrp.yaml
  - override /callbacks: default.yaml
  - override /trainer: default.yaml
  - override /logger: csv.yaml  #wandb.yaml

env:
  num_loc: 20

logger:
  wandb:
    project: "rl4co-adv"
    tags: ["adv-am", "${env.name}"]
    group: ${env.name}${env.num_loc}
    name: am-${env.name}${env.num_loc}
    offline: True

model:
  batch_size: 512 #10 #
  val_batch_size: 1024  #10 #
  test_batch_size: 1024 #10   #
  train_data_size: 80_000  #640_000 #1_280_000  #100  #
  val_data_size: 10_000 #100  #
  test_data_size: 10_000  #100 #
  optimizer_kwargs:
    lr: 1e-4
    weight_decay: 0
  lr_scheduler:
    "MultiStepLR"
  lr_scheduler_kwargs:
    milestones: [80, 95]
    gamma: 0.1
  # policy_kwargs:
  #   test_decode_type: "multistart_sampling"

trainer:
  max_epochs: 3  #100 #3 #

seed: 1234

evaluate_method: "greedy"   #["greedy", "sampling", "greedy_multistart", "augment_dihedral_8", "augment", "greedy_multistart_augment_dihedral_8", "greedy_multistart_augment"]