# @package _global_

# default evaluate setup
# other evaluate configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "evaluate"

# disable callbacks and loggers during debugging
callbacks: null

train: False

test: False 

mode: "evaluate"
evaluate: true

eval_withadv: false
trained_rarl_prog: true
# in evaluate mode, must give these params!!!!!
# evaluate_savedir: "/home/panpan/rl4co/logs/train/runs/tsp50/am-tsp50/2023-12-29_09-28-33"
# ckpt_path: "/home/panpan/rl4co/logs/train/runs/tsp50/am-tsp50/2023-12-29_09-28-33/rl4co/mql00v5r/checkpoints/epoch=2-step=3.ckpt"
evaluate_savedir: "/home/panpan/rl4co/logs/train_rarl/runs/svrp20/am-svrp20/2024-01-10_09-56-02"
ckpt_rarl_path: "/home/panpan/rl4co/logs/train_rarl/runs/svrp20/am-svrp20/2024-01-10_09-56-02/csv/version_0/checkpoints/epoch=149-step=975000.ckpt"
ckpt_prog_path: "/home/panpan/rl4co/logs/train/runs/svrp20/am-svrp20/2024-01-09_08-39-55/rl4co/hmn0gzmw/checkpoints/epoch=99-step=250000.ckpt"
evaluate_loc: "${evaluate_savedir}"
evaluate_method: "greedy"   # ["greedy", "sampling", "greedy_multistart", "augment_dihedral_8", "augment", "greedy_multistart_augment_dihedral_8", "greedy_multistart_augment"]

