# @package _global_

defaults:
  - override /model: am.yaml
  - override /env: svrp.yaml
  - override /callbacks: default.yaml
  - override /trainer: default.yaml
  - override /logger: wandb.yaml

env:
  num_loc: 20

logger:
  wandb:
    project: "rl4co"
    tags: ["am", "${env.name}"]
    group: ${env.name}${env.num_loc}
    name: am-${env.name}${env.num_loc}
    offline: True

model:
  batch_size: 10 #512
  val_batch_size: 10 #1024
  test_batch_size: 10   #1024
  train_data_size: 100  #1_280_000
  val_data_size: 100  #10_000
  test_data_size: 100 #10_000
  optimizer_kwargs:
    lr: 1e-4
    weight_decay: 0
  lr_scheduler:
    "MultiStepLR"
  lr_scheduler_kwargs:
    milestones: [80, 95]
    gamma: 0.1

trainer:
  max_epochs: 3  #100

seed: 1234

