# @package _global_

# Use the following to take the default values from am.yaml
# Replace below only the values that you want to change compared to the default values
defaults:
  - svrp_routing/am_svrp.yaml

logger:
  wandb:
    tags: ["am-critic", "${env.name}"]
    name: am-critic-${env.name}${env.num_loc}

model:
  baseline: "critic"